export enum SocketRoom {
  INVOICE = 'INVOICE',
  QUOTATION = 'QUOTATION',
  DELIVERY_NOTE = 'DELIVERY_NOTE',
  GOODS_ISSUE_NOTE = 'GOODS_ISSUE_NOTE',
  CUSTOMER_ORDER = 'CUSTOMER_ORDER',
  CREDIT_NOTE = 'CREDIT_NOTE',
  RETURN_NOTE = 'RETURN_NOTE',
  LOGGER = 'LOGGER'
}
