CREATE TABLE IF NOT EXISTS `templates` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `content` LONGTEXT DEFAULT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  `isDeletionRestricted` BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `template-styles` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL UNIQUE,
  `content` LONGTEXT DEFAULT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  `isDeletionRestricted` BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `template_template_styles` (
  `templateId` VARCHAR(36) NOT NULL,
  `styleId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`templateId`, `styleId`),
  CONSTRAINT `FK_template_template_styles_templateId` FOREIGN KEY (`templateId`) REFERENCES `templates` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_template_template_styles_styleId` FOREIGN KEY (`styleId`) REFERENCES `template-styles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);
