export enum AI_INTENT {
  ANSWER_BUSINESS_QUESTION = 'ANSWER_BUSINESS_QUESTION',
  GENERATE_CHART = 'GENERATE_CHART',
  CREATE_INVOICE_DRAFT = 'CREATE_INVOICE_DRAFT',
  CREATE_QUOTE_DRAFT = 'CREATE_QUOTE_DRAFT',
  CREATE_CUSTOMER = 'CREATE_CUSTOMER',
  CREATE_PAYMENT = 'CREATE_PAYMENT',
  TRANSFORM_QUOTE_TO_INVOICE = 'TRANSFORM_QUOTE_TO_INVOICE',
  ANALYZE_SUPPLIER_INVOICE = 'ANALYZE_SUPPLIER_INVOICE',
  SUMMARIZE_DASHBOARD = 'SUMMARIZE_DASHBOARD',
  EXPLAIN_ENTITY = 'EXPLAIN_ENTITY',
  UNKNOWN_INTENT = 'UNKNOWN_INTENT',
}
