/**
 * Deterministic demo data definitions.
 * All names/references use DEMO- prefix for safe identification and cleanup.
 */

import { ARTICLE_TYPE } from 'src/modules/article/enums/article-type.enum';
import { ARTICLE_DESTINATION } from 'src/modules/article/enums/article-destination.enum';
import { SOCIAL_TITLES } from 'src/app/enums/social-titles.enum';

// ─── Prefix ──────────────────────────────────────────────────────────────────
export const DEMO_PREFIX = 'DEMO-';

// ─── Clients (20) ────────────────────────────────────────────────────────────
export const DEMO_CLIENTS = [
  {
    name: 'DEMO-Société Alpha Tech',
    phone: '+216 71 100 001',
    taxId: 'TN10001',
    isPerson: false,
  },
  {
    name: 'DEMO-Entreprise BetaCom',
    phone: '+216 71 100 002',
    taxId: 'TN10002',
    isPerson: false,
  },
  {
    name: 'DEMO-Groupe Gamma Industries',
    phone: '+216 71 100 003',
    taxId: 'TN10003',
    isPerson: false,
  },
  {
    name: 'DEMO-Delta Services SARL',
    phone: '+216 71 100 004',
    taxId: 'TN10004',
    isPerson: false,
  },
  {
    name: 'DEMO-Epsilon Consulting',
    phone: '+216 71 100 005',
    taxId: 'TN10005',
    isPerson: false,
  },
  {
    name: 'DEMO-Zeta Trading Co.',
    phone: '+216 71 100 006',
    taxId: 'TN10006',
    isPerson: false,
  },
  {
    name: 'DEMO-Eta Solutions',
    phone: '+216 71 100 007',
    taxId: 'TN10007',
    isPerson: false,
  },
  {
    name: 'DEMO-Theta Digital',
    phone: '+216 71 100 008',
    taxId: 'TN10008',
    isPerson: false,
  },
  {
    name: 'DEMO-Iota Logistics',
    phone: '+216 71 100 009',
    taxId: 'TN10009',
    isPerson: false,
  },
  {
    name: 'DEMO-Kappa Pharma',
    phone: '+216 71 100 010',
    taxId: 'TN10010',
    isPerson: false,
  },
  {
    name: 'DEMO-Lambda Construction',
    phone: '+216 71 100 011',
    taxId: 'TN10011',
    isPerson: false,
  },
  {
    name: 'DEMO-Mu Import-Export',
    phone: '+216 71 100 012',
    taxId: 'TN10012',
    isPerson: false,
  },
  {
    name: 'DEMO-Nu Électronique',
    phone: '+216 71 100 013',
    taxId: 'TN10013',
    isPerson: false,
  },
  {
    name: 'DEMO-Xi Automobile',
    phone: '+216 71 100 014',
    taxId: 'TN10014',
    isPerson: false,
  },
  {
    name: 'DEMO-Omicron Textiles',
    phone: '+216 71 100 015',
    taxId: 'TN10015',
    isPerson: false,
  },
  {
    name: 'DEMO-Pi Alimentaire',
    phone: '+216 71 100 016',
    taxId: 'TN10016',
    isPerson: false,
  },
  {
    name: 'DEMO-Rho Immobilier',
    phone: '+216 71 100 017',
    taxId: 'TN10017',
    isPerson: false,
  },
  {
    name: 'DEMO-Sigma Énergie',
    phone: '+216 71 100 018',
    taxId: 'TN10018',
    isPerson: false,
  },
  {
    name: 'DEMO-Ahmed Ben Salah',
    phone: '+216 98 100 001',
    taxId: '',
    isPerson: true,
  },
  {
    name: 'DEMO-Fatma Trabelsi',
    phone: '+216 98 100 002',
    taxId: '',
    isPerson: true,
  },
];

// ─── Suppliers (15) ──────────────────────────────────────────────────────────
export const DEMO_SUPPLIERS = [
  {
    name: 'DEMO-Fournisseur Acier Plus',
    phone: '+216 71 200 001',
    taxId: 'TN20001',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur Bois & Matériaux',
    phone: '+216 71 200 002',
    taxId: 'TN20002',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur ChimiPro',
    phone: '+216 71 200 003',
    taxId: 'TN20003',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur DistriPack',
    phone: '+216 71 200 004',
    taxId: 'TN20004',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur ElectroParts',
    phone: '+216 71 200 005',
    taxId: 'TN20005',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur FabriquePlus',
    phone: '+216 71 200 006',
    taxId: 'TN20006',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur GlobalSupply',
    phone: '+216 71 200 007',
    taxId: 'TN20007',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur HydroTech',
    phone: '+216 71 200 008',
    taxId: 'TN20008',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur InfoMat',
    phone: '+216 71 200 009',
    taxId: 'TN20009',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur JardinVert',
    phone: '+216 71 200 010',
    taxId: 'TN20010',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur KéramPro',
    phone: '+216 71 200 011',
    taxId: 'TN20011',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur LumiTech',
    phone: '+216 71 200 012',
    taxId: 'TN20012',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur MétallurgiePlus',
    phone: '+216 71 200 013',
    taxId: 'TN20013',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur NetPro',
    phone: '+216 71 200 014',
    taxId: 'TN20014',
    isPerson: false,
  },
  {
    name: 'DEMO-Fournisseur OptiFourniture',
    phone: '+216 71 200 015',
    taxId: 'TN20015',
    isPerson: false,
  },
];

// ─── Interlocutors (one per firm) ────────────────────────────────────────────
export const DEMO_INTERLOCUTORS = [
  // Client interlocutors (20)
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Ali',
    surname: 'Mansouri',
    email: 'ali.mansouri@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Leila',
    surname: 'Bouazizi',
    email: 'leila.bouazizi@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Karim',
    surname: 'Gharbi',
    email: 'karim.gharbi@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Sonia',
    surname: 'Haddad',
    email: 'sonia.haddad@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Mehdi',
    surname: 'Jouini',
    email: 'mehdi.jouini@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Nabil',
    surname: 'Khalfi',
    email: 'nabil.khalfi@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Rania',
    surname: 'Lagha',
    email: 'rania.lagha@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Samir',
    surname: 'Mbarki',
    email: 'samir.mbarki@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Nour',
    surname: 'Nasri',
    email: 'nour.nasri@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Omar',
    surname: 'Oueslati',
    email: 'omar.oueslati@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Riadh',
    surname: 'Pasha',
    email: 'riadh.pasha@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Salma',
    surname: 'Riahi',
    email: 'salma.riahi@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Tarek',
    surname: 'Saidani',
    email: 'tarek.saidani@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Ines',
    surname: 'Turki',
    email: 'ines.turki@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Walid',
    surname: 'Zairi',
    email: 'walid.zairi@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Youssef',
    surname: 'Abdallah',
    email: 'youssef.abdallah@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Amira',
    surname: 'Belhaj',
    email: 'amira.belhaj@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Hatem',
    surname: 'Chouchane',
    email: 'hatem.chouchane@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Ahmed',
    surname: 'Ben Salah',
    email: 'ahmed.bensalah@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Fatma',
    surname: 'Trabelsi',
    email: 'fatma.trabelsi@demo.tn',
  },
  // Supplier interlocutors (15)
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Firas',
    surname: 'Derbel',
    email: 'firas.derbel@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Hela',
    surname: 'Essid',
    email: 'hela.essid@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Jamel',
    surname: 'Ferchichi',
    email: 'jamel.ferchichi@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Khadija',
    surname: 'Gueddich',
    email: 'khadija.gueddich@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Lotfi',
    surname: 'Hammami',
    email: 'lotfi.hammami@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Mourad',
    surname: 'Jelassi',
    email: 'mourad.jelassi@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Najet',
    surname: 'Kacem',
    email: 'najet.kacem@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Oussama',
    surname: 'Lahmar',
    email: 'oussama.lahmar@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Rim',
    surname: 'Maalej',
    email: 'rim.maalej@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Slim',
    surname: 'Nasr',
    email: 'slim.nasr@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Taoufik',
    surname: 'Othmani',
    email: 'taoufik.othmani@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Wafa',
    surname: 'Rebai',
    email: 'wafa.rebai@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Zied',
    surname: 'Sassi',
    email: 'zied.sassi@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MRS,
    name: 'DEMO-Asma',
    surname: 'Tlili',
    email: 'asma.tlili@demo.tn',
  },
  {
    title: SOCIAL_TITLES.MR,
    name: 'DEMO-Bilel',
    surname: 'Yacoubi',
    email: 'bilel.yacoubi@demo.tn',
  },
];

// ─── Articles / Services (30) ────────────────────────────────────────────────
export const DEMO_ARTICLES: {
  title: string;
  reference: string;
  type: ARTICLE_TYPE;
  destination: ARTICLE_DESTINATION;
  salePrice: number;
  purchasePrice: number;
  unit: string;
  family: string;
}[] = [
  // Products (20)
  {
    title: 'DEMO-Ordinateur portable Pro 15"',
    reference: 'DEMO-ART-001',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 2850,
    purchasePrice: 1900,
    unit: 'Unité',
    family: 'Informatique',
  },
  {
    title: 'DEMO-Écran moniteur 27" 4K',
    reference: 'DEMO-ART-002',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 1200,
    purchasePrice: 750,
    unit: 'Unité',
    family: 'Informatique',
  },
  {
    title: 'DEMO-Imprimante laser A4',
    reference: 'DEMO-ART-003',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 680,
    purchasePrice: 420,
    unit: 'Unité',
    family: 'Informatique',
  },
  {
    title: 'DEMO-Clavier mécanique sans fil',
    reference: 'DEMO-ART-004',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 180,
    purchasePrice: 95,
    unit: 'Unité',
    family: 'Accessoires',
  },
  {
    title: 'DEMO-Souris ergonomique BT',
    reference: 'DEMO-ART-005',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 85,
    purchasePrice: 42,
    unit: 'Unité',
    family: 'Accessoires',
  },
  {
    title: 'DEMO-Câble réseau Cat6 (100m)',
    reference: 'DEMO-ART-006',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.BOTH,
    salePrice: 120,
    purchasePrice: 65,
    unit: 'Bobine',
    family: 'Réseau',
  },
  {
    title: 'DEMO-Switch réseau 24 ports',
    reference: 'DEMO-ART-007',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 950,
    purchasePrice: 620,
    unit: 'Unité',
    family: 'Réseau',
  },
  {
    title: 'DEMO-Serveur rack 2U',
    reference: 'DEMO-ART-008',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 8500,
    purchasePrice: 5800,
    unit: 'Unité',
    family: 'Serveurs',
  },
  {
    title: 'DEMO-Disque SSD 1TB NVMe',
    reference: 'DEMO-ART-009',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.BOTH,
    salePrice: 320,
    purchasePrice: 190,
    unit: 'Unité',
    family: 'Stockage',
  },
  {
    title: 'DEMO-RAM DDR5 32GB',
    reference: 'DEMO-ART-010',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 280,
    purchasePrice: 170,
    unit: 'Barrette',
    family: 'Composants',
  },
  {
    title: 'DEMO-Onduleur 1500VA',
    reference: 'DEMO-ART-011',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 450,
    purchasePrice: 280,
    unit: 'Unité',
    family: 'Énergie',
  },
  {
    title: 'DEMO-Caméra IP surveillance',
    reference: 'DEMO-ART-012',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 350,
    purchasePrice: 195,
    unit: 'Unité',
    family: 'Sécurité',
  },
  {
    title: 'DEMO-Routeur WiFi 6',
    reference: 'DEMO-ART-013',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 520,
    purchasePrice: 310,
    unit: 'Unité',
    family: 'Réseau',
  },
  {
    title: 'DEMO-Tableau blanc interactif',
    reference: 'DEMO-ART-014',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 3200,
    purchasePrice: 2100,
    unit: 'Unité',
    family: 'Présentation',
  },
  {
    title: 'DEMO-Vidéoprojecteur Full HD',
    reference: 'DEMO-ART-015',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 1800,
    purchasePrice: 1100,
    unit: 'Unité',
    family: 'Présentation',
  },
  {
    title: 'DEMO-Disque dur externe 4TB',
    reference: 'DEMO-ART-016',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 280,
    purchasePrice: 165,
    unit: 'Unité',
    family: 'Stockage',
  },
  {
    title: 'DEMO-Pack licence Office 365',
    reference: 'DEMO-ART-017',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 450,
    purchasePrice: 320,
    unit: 'Licence',
    family: 'Logiciel',
  },
  {
    title: 'DEMO-Antivirus entreprise (10 postes)',
    reference: 'DEMO-ART-018',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 380,
    purchasePrice: 220,
    unit: 'Licence',
    family: 'Logiciel',
  },
  {
    title: "DEMO-Station d'accueil USB-C",
    reference: 'DEMO-ART-019',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 160,
    purchasePrice: 90,
    unit: 'Unité',
    family: 'Accessoires',
  },
  {
    title: 'DEMO-Casque audio professionnel',
    reference: 'DEMO-ART-020',
    type: ARTICLE_TYPE.PRODUCT,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 220,
    purchasePrice: 130,
    unit: 'Unité',
    family: 'Accessoires',
  },
  // Services (10)
  {
    title: 'DEMO-Installation réseau complet',
    reference: 'DEMO-SRV-001',
    type: ARTICLE_TYPE.SERVICE,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 2500,
    purchasePrice: 0,
    unit: 'Forfait',
    family: 'Infrastructure',
  },
  {
    title: 'DEMO-Maintenance informatique mensuelle',
    reference: 'DEMO-SRV-002',
    type: ARTICLE_TYPE.SERVICE,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 800,
    purchasePrice: 0,
    unit: 'Mois',
    family: 'Support',
  },
  {
    title: 'DEMO-Formation bureautique (1 jour)',
    reference: 'DEMO-SRV-003',
    type: ARTICLE_TYPE.SERVICE,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 600,
    purchasePrice: 0,
    unit: 'Jour',
    family: 'Formation',
  },
  {
    title: 'DEMO-Développement web sur mesure',
    reference: 'DEMO-SRV-004',
    type: ARTICLE_TYPE.SERVICE,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 1500,
    purchasePrice: 0,
    unit: 'Jour/homme',
    family: 'Développement',
  },
  {
    title: 'DEMO-Audit sécurité informatique',
    reference: 'DEMO-SRV-005',
    type: ARTICLE_TYPE.SERVICE,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 3500,
    purchasePrice: 0,
    unit: 'Mission',
    family: 'Sécurité',
  },
  {
    title: 'DEMO-Hébergement cloud (mensuel)',
    reference: 'DEMO-SRV-006',
    type: ARTICLE_TYPE.SERVICE,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 350,
    purchasePrice: 0,
    unit: 'Mois',
    family: 'Cloud',
  },
  {
    title: 'DEMO-Migration données ERP',
    reference: 'DEMO-SRV-007',
    type: ARTICLE_TYPE.SERVICE,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 4500,
    purchasePrice: 0,
    unit: 'Forfait',
    family: 'Consulting',
  },
  {
    title: 'DEMO-Support technique premium',
    reference: 'DEMO-SRV-008',
    type: ARTICLE_TYPE.SERVICE,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 1200,
    purchasePrice: 0,
    unit: 'Trimestre',
    family: 'Support',
  },
  {
    title: 'DEMO-Conseil stratégie digitale',
    reference: 'DEMO-SRV-009',
    type: ARTICLE_TYPE.SERVICE,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 2000,
    purchasePrice: 0,
    unit: 'Jour',
    family: 'Consulting',
  },
  {
    title: 'DEMO-Sauvegarde cloud automatique',
    reference: 'DEMO-SRV-010',
    type: ARTICLE_TYPE.SERVICE,
    destination: ARTICLE_DESTINATION.SELLING,
    salePrice: 250,
    purchasePrice: 0,
    unit: 'Mois',
    family: 'Cloud',
  },
];

// ─── Bank accounts (multiple for treasury) ───────────────────────────────────
export const DEMO_BANK_ACCOUNTS = [
  {
    name: 'DEMO-Banque Principale TND',
    rib: '12345678901234567890',
    iban: 'TN5912345678901234567890',
    bic: 'BIATTNTT',
    agency: 'Agence Tunis Centre',
    type: 'bank' as const,
    isMain: true,
  },
  {
    name: 'DEMO-Banque Secondaire STB',
    rib: '09876543210987654321',
    iban: 'TN5909876543210987654321',
    bic: 'STBKTNTT',
    agency: 'Agence La Marsa',
    type: 'bank' as const,
    isMain: false,
  },
  {
    name: 'DEMO-Caisse Principale',
    rib: '',
    iban: '',
    bic: '',
    agency: '',
    type: 'cash' as const,
    isMain: false,
  },
  {
    name: 'DEMO-Caisse Secondaire',
    rib: '',
    iban: '',
    bic: '',
    agency: '',
    type: 'cash' as const,
    isMain: false,
  },
];

// Keep backward compatibility
export const DEMO_BANK_ACCOUNT = DEMO_BANK_ACCOUNTS[0];

// ─── Withholding tax rates ───────────────────────────────────────────────────
export const DEMO_WITHHOLDING_TAXES = [
  { label: 'DEMO-Retenue 1.5%', rate: 1.5 },
  { label: 'DEMO-Retenue 3%', rate: 3 },
  { label: 'DEMO-Retenue 5%', rate: 5 },
  { label: 'DEMO-Retenue 10%', rate: 10 },
  { label: 'DEMO-Retenue 15%', rate: 15 },
];
